---
    tasks:
        - name: "Task1"
          import: "tasks"

        - name: "Task2"
          import: "tasks"

        - name: "Task3"
          import: "tasks"

        - name: "Task4"
          import: "tasks"

        - name: "Task5"
          import: "tasks"


    flows:
        - "flow1"
        - "flow2"

