---
    tasks:
        - name: "FactTask"
          import: "tasks"
          storage: "SqlStorage"
        - name: "SumTask"
          import: "tasks"
          storage: "RedisStorage"
        - name: "MulTask"
          import: "tasks"
          storage: "MongoStorage"
        - name: "FallbackTask"
          import: "tasks"

    flows:
        - "mainFlow"
        - "factorialFlow"


    storages:
        - name: "SqlStorage"
          import: "celeriac.storage"
          configuration:
            connection_string: 'postgres://postgres:postgres@postgres:5432/postgres'

        - name: "RedisStorage"
          import: "celeriac.storage"
          configuration:
            host: 'redis'
            port: 6379
            db: 1
            charset: 'utf-8'

        - name: "MongoStorage"
          import: "celeriac.storage"
          configuration:
            db_name: 'database_name'
            collection_name: 'collection_name'
            host: 'mongo'
            port: 27017

