---
    flow-definitions:
        - name: "flow1"
          edges:
              - from:
                to:
                  - "Task1"
                condition:
                    name: "alwaysTrue"

              - from:
                  - "Task1"
                to:
                  - "Task2"
                  - "flow2"
                condition:
                    name: "alwaysTrue"
                    node: "Task1"

